### PR TITLE
Fix build on Windows

### PR DESCRIPTION
**Pull request by gaborcsardi**
Mostly straightforward, and I left some comments in the code that hopefully explain the motivation for some of the more obscure bits. 

The cross compiling of grpc breaks the loading of the grpc root certificates, so we embed them into the package on Windows, and set an env var at load time to point to it.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
The Ubuntu R-devel CI failure is unrelated and will be fixed, once the new version of the progress package is on CRAN, in a couple of hours, hopefully.

**Comment by gaborcsardi** [comment]
> 
The Ubuntu R-devel CI failure is unrelated and will be fixed, once the new version of the progress package is on CRAN, in a couple of hours, hopefully.

Oh, it is not coming from the progress package, it seems, let me merge main.

**Comment by meztez** [comment]
@gaborcsardi I will switch to the CRAN version. I think at the time I had issue with Windows Rstudio and needed an extra field to display throttle state. I prefer using progress header directly from the package for an release.

**Comment by meztez** [comment]
[celebrate]     Bruno Tremblay reacted to your message:
________________________________

**Pull request merged**
