### PR TITLE
rtools43 now has grpc

### PR DESCRIPTION
**Pull request by meztez**

### CODE REVIEW

**Comment by meztez** [comment]
seems like rtools42 not supported?

**Comment by gaborcsardi** [comment]
No, they won't update rtool42. So if we want to support that, which would be good, then we still need to download grpc for that. But I _think_ that's ok. Or we can require R 4.3. on Windows.

**Comment by meztez** [comment]
> No, they won't update rtool42. So if we want to support that, which would be good, then we still need to download grpc for that. But I _think_ that's ok. Or we can require R 4.3. on Windows.

I wonder if the submission will be declined if it includes code to download lib from the internet like last time.

**Comment by gaborcsardi** [comment]
Yeah, probably better not to download this time.

**Pull request merged**
